# Generated by Django 4.0.2 on 2022-09-26 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(verbose_name='數量')),
                ('in_time', models.DateField(auto_now_add=True, verbose_name='進貨時間')),
                ('out_time', models.DateField(auto_now=True, verbose_name='銷貨時間')),
                ('price', models.IntegerField(default=0, verbose_name='銷貨金額')),
            ],
            options={
                'db_table': 'products_inout',
            },
        ),
        migrations.CreateModel(
            name='ProductProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=10, verbose_name='品牌')),
                ('type_no', models.CharField(max_length=50, verbose_name='型號')),
                ('kind', models.CharField(max_length=20, verbose_name='類別')),
                ('total', models.IntegerField(default=0, verbose_name='商品總數')),
            ],
            options={
                'db_table': 'products_file',
            },
        ),
        migrations.CreateModel(
            name='ProductReceipt',
            fields=[
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.productmanager')),
                ('status', models.IntegerField(default=0, verbose_name='發票狀態')),
                ('make_time', models.DateField(auto_now=True, verbose_name='開發票時間')),
            ],
            options={
                'db_table': 'products_receipt',
            },
        ),
        migrations.AddField(
            model_name='productmanager',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productprofile'),
        ),
    ]
